[project]
name = "hemosc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pedro Guardini", email = "pgabiattiguardini@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "pandas>=3.0.5",
    "sqlmodel>=0.0.42",
    "streamlit>=1.63.0",
]

[project.scripts]
hemosc = "hemosc:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
